config/routes.rb
Htk::Application.routes.draw do
  namespace :api do
    namespace :v1 do
      resources :email_comments
      resources :signed_request_users, only: [:create]
      resources :deliverables do
        resources :comments, controller: 'deliverable_comments'
        resources :permissions, only: [:create, :destroy, :update], controller: 'deliverables/permissions'
      end
      resources :deliverable_relations
      resources :users, only: [:index, :show]
      resources :messages, only: [:index]
      resources :emails, only: [:index]
      resources :deliverable_types, :only => :index
      resources :companies, controller: 'deliverables/companies'
    end
  end 

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  devise_for :users, path: "auth"
  resources :emails

  resources :messages, :only => [:index, :show, :update, :destroy]

  resources :deliverables
  match 'dashboard' => 'deliverables#dashboard'

  resources :users

  resource :gplus_auths, only: :show do
    post 'connect'
    post 'disconnect'
    get 'profile'
  end

  match 'signin', to: 'signin#signin'

  root :to => "home#index"

end

app/controllers/gplus_auths_controller.rb
class GplusAuthsController < ApplicationController
	skip_before_filter :verify_authenticated_user!

	def connect
    google_authorization = GoogleAuthorization.find_or_build(request.body.read)
    user = google_authorization.user || User.new
  	google_authorization.with_client! do |client| 
  		response = client.execute!(client.discovered_api('plus', 'v1').people.get, { userId: 'me' })
  		person = JSON.parse(response.body)
  		user.email = person['emails'].first['value']
  		name = person['name']
  		user.first_name = name['givenName']
  		user.last_name = name['familyName']
		end
		User.connection.transaction do
	    user.save!
	    google_authorization.user_id = user.id
	    google_authorization.save!
	    sign_in user
	  end
    if true
	    render text: '', status: 200
    else
			render json: { error: 'The client state does not match the server state.' }, status: 401
    end
	  # end
	end

	def disconnect
		if ga = current_user.google_authorization
		  render text: '', status: ga.disconnect
		else
		  render text: 'No stored credentials', status: 401
		end
	end

	def profile
		begin
			response = current_user.google_authorization.with_client! do |c| 
				c.execute!(c.discovered_api('plus', 'v1').people.get, { userId: 'me' }) 
			end
			render json: JSON.parse(response.body), status: 200
		rescue Google::APIClient::TransmissionError => e
			if e.result.status == 401
				log_error "Signing out user"
				sign_out
			end
			render json: { error: e.result.error_message }, status: e.result.status
		rescue => e
			log_error "Unhandled error", e
			render json: { error: e.message }, status: 500
		end
	end
end

app/views/gplus_auths/_signin.html.erb
<div id="gConnect">
  <button class="g-signin"
      data-scope="<%= AppConfig.gplus_signin_scope.join(' ') %>"
      data-requestvisibleactions="http://schemas.google.com/AddActivity"
      data-clientId="<%= gplus_credentials.client_id %>"
      data-accesstype="offline"
      data-callback="onSignInCallback"
      data-theme="dark"
      data-cookiepolicy="single_host_origin"
      data-approvalprompt="<%= params.member?(:force) ? 'force' : 'auto' %>">
  </button>
</div>
<div id="login-spin" class="hidden">
	<%= image_tag "small_spinning_icon.gif" %>
</div>
<div id="authOps" style="display:none">
  <h2>Authentication Logs</h2>
  <pre id="authResult"></pre>
</div>

<input type="hidden" name="redirect_url" value=<%= @redirect_url %> />

<% content_for :javascripts do %>
<script type="text/javascript">

var count = 0;
function onSignInCallback(authResult) {
  if (authResult['access_token']) {
    // The user is signed in
    console.log(authResult.code);
    $('#gConnect').hide();
    $("#authResult").hide();
    $("#login-spin").show();
    $.ajax({
      type: 'POST',
      url: "<%= connect_gplus_auths_url %>",
      contentType: 'application/octet-stream; charset=utf-8',
      success: function(result) {
        console.log(result);
		    var redirect_url = $("input[name=redirect_url]").val();
		    if (!redirect_url) {
		      redirect_url = "<%= root_url %>";
		    }
        console.log("Would redirect to " + redirect_url);
		    window.location = redirect_url;
      },
      processData: false,
      data: authResult.code
    });
  } else if (authResult['error']) {
    if (authResult['error'] == 'user_signed_out')
    $("#login-spin").hide();
    $('#authResult').empty().html('Auth Result:<br/>');
    for (var field in authResult) {
      $('#authResult').append(' ' + field + ': ' + authResult[field] + '<br/>');
    }
    console.log('There was an error: ' + authResult['error']);
    $('#authResult').append('Logged out');
    $('#authOps').show('slow');
    $('#gConnect').show();
  }
  console.log('authResult', authResult);
}

(function() {
  var po = document.createElement('script');
  po.type = 'text/javascript'; po.async = true;
  po.src = 'https://plus.google.com/js/client:plusone.js';
  var s = document.getElementsByTagName('script')[0];
  s.parentNode.insertBefore(po, s);
})();

</script>
<% end %>

app/views/gplus_auths/_user_click_gapi.html.erb
<div id="click-me" style="display:none">
  <p>Click Me!!!</p>
</div>

<div id="profile">
  <div id="profile-spin">
    <%= image_tag "big_spinning_icon.gif" %>
  </div>
</div>

<meta name="google-signin-clientid" content="<%= gplus_credentials.client_id %>" />
<meta name="google-signin-scope" content="<%= AppConfig.gplus_signin_scope %>" />
<meta name="google-signin-requestvisibleactions" content="http://schema.org/AddAction" />
<meta name="google-signin-cookiepolicy" content="single_host_origin" />

<% content_for :javascripts do %>
<script type="text/javascript">
var count = 0;
function onSignInCallback(authResult) {
  $("#profile-spin").hide();
  console.log('authResult', authResult);
  if (authResult['status']['signed_in']) {
    if (authResult['access_token']) {
      gapi.client.load('plus','v1',renderProfile);
    }
  } else if (authResult['error']) {
    console.log('There was an error: ' + authResult['error']);
  }
}

function renderProfile() {
  var request = gapi.client.plus.people.get( {'userId' : 'me'} );
  request.execute( function(profile) {
    $('#profile').empty();
    if (profile.error) {
      $('#profile').append(profile.error);
      return;
    }
    $('#profile').append(
        $('<p><img src=\"' + profile.image.url + '\"></p>'));
    $('#profile').append(
        $('<p>Hello ' + profile.displayName + '!<br />Tagline: ' +
        profile.tagline + '<br />About: ' + profile.aboutMe + '</p>'));
    if (profile.cover && profile.coverPhoto) {
      $('#profile').append(
          $('<p><img src=\"' + profile.cover.coverPhoto.url + '\"></p>'));
    }
  });
}

function plusoneLoaded() {
  $("#profile-spin").hide();
  $("#click-me").show().click(function() {
    $(this).hide();
    $("#profile-spin").show();
    gapi.auth.signIn({ 'callback' : onSignInCallback });  
  });
}

(function() {
  var po = document.createElement('script');
  po.type = 'text/javascript'; po.async = true;
  po.src = 'https://plus.google.com/js/client:plusone.js?onload=plusoneLoaded';
  var s = document.getElementsByTagName('script')[0];
  s.parentNode.insertBefore(po, s);
})();

</script>
<% end %>