config/routes.rb
Htk::Application.routes.draw do
  namespace :api do
    namespace :v1 do
      resources :email_comments
      resources :signed_request_users, only: [:create]
      resources :deliverables do
        resources :comments, controller: 'deliverable_comments'
        resources :permissions, only: [:create, :destroy, :update], controller: 'deliverables/permissions'
      end
      resources :deliverable_relations
      resources :users, only: [:index, :show]
      resources :messages, only: [:index]
      resources :emails, only: [:index]
      resources :deliverable_types, :only => :index
      resources :companies, controller: 'deliverables/companies'
    end
  end 

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  devise_for :users, path: "auth"
  resources :emails

  resources :messages, :only => [:index, :show, :update, :destroy]

  resources :deliverables
  match 'dashboard' => 'deliverables#dashboard'

  resources :users

  resource :gplus_auths, only: :show do
    post 'connect'
    post 'disconnect'
    get 'profile'
  end

  match 'signin', to: 'signin#signin'

  root :to => "home#index"

end

app/views/layouts/_navigation.html.erb
<!-- Fixed navbar -->
<div class="navbar navbar-inverse navbar-fixed-top" role="navigation">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="/">HTK</a>
    </div>
    <div class="navbar-collapse collapse">
      <ul class="nav navbar-nav">
        <li><a href="#about">About</a></li>
        <li><a href="#contact">Contact</a></li>
        <% if current_user %>
        <li class="<%= menu_selected(:deliverables) %>"><%= link_to 'Deliverables', dashboard_url %></li>
        <li class="<%= menu_selected(:inbox) %>"><%= link_to 'Inbox', emails_url %></li>
        <li class="dropdown">
        <a href="#account" class="dropdown-toggle" data-toggle="dropdown">Account <span class="caret"></span></a>
          <ul class="dropdown-menu" role="menu">
            <li><%= link_to 'Settings', user_url(current_user) %></li>
            <li><%= link_to 'Logout', destroy_user_session_url, :method => :delete  %></li>
          </ul>
        </li>
        <% else %>
        <li class="<%= menu_selected(:login) %>"><%= link_to 'Sign In', signin_url %></li>
        <% end %>
      </ul>
    </div><!--/.nav-collapse -->
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>HTK</title>

    <%= stylesheet_link_tag    "application", :media => "all" %>
    <%= javascript_include_tag "application" %>
    <%= yield :stylesheets %>
    <%= csrf_meta_tag %>
    <%= yield :javascripts -%>    
  </head>
  <body role="document">
    <%= render partial: 'layouts/navigation' %>
    <div class="container theme-showcase" role="main">
      <%= yield %>
    </div>
    <div class="footer">
      <div class="container">
        <p><%= request_route_info.inspect if Rails.env.development? %></p>
      </div>
    </div>
  </body>
</html>

app/views/layouts/deliverables.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>HTK Deliverables</title>

    <%= stylesheet_link_tag    "application", :media => "all" %>
    <%= javascript_include_tag "application" %>
    <%= yield :stylesheets %>
    <%= csrf_meta_tag %>
    <%= yield :javascripts -%>
  </head>
  <body role="document">
    <%= render partial: 'layouts/navigation' %>
    <div class="container theme-showcase" role="main">
      <%= yield %>
    </div>
    <div class="footer">
      <div class="container">
        <p><%= request_route_info.inspect if Rails.env.development? %></p>
      </div>
    </div>
  </body>
</html>